// <auto-generated />
using System;
using MasterYourEnglish.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MasterYourEnglish.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Flashcard", b =>
                {
                    b.Property<int>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlashcardId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("text");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("Meaning")
                        .HasColumnType("text");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.Property<string>("Transcription")
                        .HasColumnType("text");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FlashcardId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardAttemptAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("boolean");

                    b.HasKey("AnswerId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardAttemptAnswers");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundle", b =>
                {
                    b.Property<int>("FlashcardsBundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FlashcardsBundleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFlashcardsCount")
                        .HasColumnType("integer");

                    b.HasKey("FlashcardsBundleId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("FlashcardBundles");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundleAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptId"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FlashcardsBundleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AttemptId");

                    b.HasIndex("FlashcardsBundleId");

                    b.HasIndex("UserId");

                    b.ToTable("FlashcardBundleAttempts");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundleItem", b =>
                {
                    b.Property<int>("FlashcardsBundleId")
                        .HasColumnType("integer");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("FlashcardsBundleId", "FlashcardId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("FlashcardBundleItems");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.QuestionOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptionId"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.SavedFlashcard", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "FlashcardId");

                    b.HasIndex("FlashcardId");

                    b.ToTable("SavedFlashcards");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Test", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestionsCount")
                        .HasColumnType("integer");

                    b.HasKey("TestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttempt", b =>
                {
                    b.Property<int>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptId"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AttemptId");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttemptAnswer", b =>
                {
                    b.Property<int>("AttemptAnswersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttemptAnswersId"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("UserAnswerText")
                        .HasColumnType("text");

                    b.HasKey("AttemptAnswersId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("TestAttemptAnswers");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttemptAnswerSelectedOption", b =>
                {
                    b.Property<int>("AttemptAnswersId")
                        .HasColumnType("integer");

                    b.Property<int>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptAnswersId1")
                        .HasColumnType("integer");

                    b.HasKey("AttemptAnswersId", "SelectedOptionId");

                    b.HasIndex("AttemptAnswersId1");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("TestAttemptAnswerSelectedOptions");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestQuestion", b =>
                {
                    b.Property<int>("TestId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("TestId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("TestQuestions");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Flashcard", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.User", "CreatedByUser")
                        .WithMany("Flashcards")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("MasterYourEnglish.DAL.Entities.Topic", "Topic")
                        .WithMany("Flashcards")
                        .HasForeignKey("TopicId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardAttemptAnswer", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.FlashcardBundleAttempt", "Attempt")
                        .WithMany("FlashcardsAttemptAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.Flashcard", "Flashcard")
                        .WithMany("FlashcardsAttemptAnswers")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundle", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.User", "CreatedByUser")
                        .WithMany("FlashcardsBundles")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("MasterYourEnglish.DAL.Entities.Topic", "Topic")
                        .WithMany("FlashcardsBundles")
                        .HasForeignKey("TopicId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundleAttempt", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.FlashcardBundle", "FlashcardsBundle")
                        .WithMany("FlashcardsBundleAttempts")
                        .HasForeignKey("FlashcardsBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.User", "User")
                        .WithMany("FlashcardsBundleAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlashcardsBundle");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundleItem", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.Flashcard", "Flashcard")
                        .WithMany("FlashcardsBundleItems")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.FlashcardBundle", "FlashcardsBundle")
                        .WithMany("FlashcardsBundleItems")
                        .HasForeignKey("FlashcardsBundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("FlashcardsBundle");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Question", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.User", "CreatedByUser")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("MasterYourEnglish.DAL.Entities.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.QuestionOption", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.SavedFlashcard", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.Flashcard", "Flashcard")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.User", "User")
                        .WithMany("SavedFlashcards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Test", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.User", "CreatedByUser")
                        .WithMany("Tests")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("MasterYourEnglish.DAL.Entities.Topic", "Topic")
                        .WithMany("Tests")
                        .HasForeignKey("TopicId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttempt", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.Test", "Test")
                        .WithMany("TestAttempts")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttemptAnswer", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.TestAttempt", "Attempt")
                        .WithMany("TestAttemptsAnswers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.Question", "Question")
                        .WithMany("TestAttemptsAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId");

                    b.Navigation("Attempt");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttemptAnswerSelectedOption", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.TestAttemptAnswer", "AttemptAnswer")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("AttemptAnswersId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.QuestionOption", "SelectedOption")
                        .WithMany("SelectedInAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttemptAnswer");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestQuestion", b =>
                {
                    b.HasOne("MasterYourEnglish.DAL.Entities.Question", "Question")
                        .WithMany("TestQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasterYourEnglish.DAL.Entities.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Flashcard", b =>
                {
                    b.Navigation("FlashcardsAttemptAnswers");

                    b.Navigation("FlashcardsBundleItems");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundle", b =>
                {
                    b.Navigation("FlashcardsBundleAttempts");

                    b.Navigation("FlashcardsBundleItems");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.FlashcardBundleAttempt", b =>
                {
                    b.Navigation("FlashcardsAttemptAnswers");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Question", b =>
                {
                    b.Navigation("QuestionOptions");

                    b.Navigation("TestAttemptsAnswers");

                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.QuestionOption", b =>
                {
                    b.Navigation("SelectedInAnswers");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Test", b =>
                {
                    b.Navigation("TestAttempts");

                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttempt", b =>
                {
                    b.Navigation("TestAttemptsAnswers");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.TestAttemptAnswer", b =>
                {
                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.Topic", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("FlashcardsBundles");

                    b.Navigation("Questions");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("MasterYourEnglish.DAL.Entities.User", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("FlashcardsBundleAttempts");

                    b.Navigation("FlashcardsBundles");

                    b.Navigation("Questions");

                    b.Navigation("SavedFlashcards");

                    b.Navigation("TestAttempts");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
